### ISSUE TITLE
Open with single click

### ISSUE THREAD

**Issue by patrickvuarnoz** [gejobj/tablist#1]
Hi Gerardo, that's an interesting Nova extension that you're working on. For me it solves the problem where after opening more than 5 tabs I cannot read the filename anymore. Nova does not offer a good solution for that. But your extension shows how it can be improved greatly! Reminds me of Brackets.

I'd have two suggestions for you:

- Switching to the tab with a single click would feel simpler (maybe make it a config option if you prefer a double click)
- It would be great if you could show the file path on hover like Nova already does on the tab titles. That would help to identify the right tab when you happen to have multiple files open with the same name (like index.html or config.js).

**Comment by gejobj** [comment]
Thank you so much for your feedback.
I will add your suggestions and a few ideas I still have and I will try to implement them into the extension as soon as I can.
Best regards :-)

**Comment by gejobj** [comment]
TabList 1.0.2 version uploaded to Nova Extension Library with your suggestions :-)
Thanks!

**Comment by patrickvuarnoz** [comment]
Cool, thanks! I also like the idea of grouping by file type. 

There seems to be a bug in the non-grouped view. I cannot click on the file there, i.e. nothing happens when I click. Maybe you introduced that with version 2.0.

**Comment by gejobj** [comment]
Hi!
ups! I found the bug. I will try to fix it as soon as I can.
Thanks for your feedback.

**Comment by gejobj** [comment]
I fixed the bug in ungrouped mode in 2.0.1 version.
Thanks again for your feedbacks. They are very helpful.
Best regards!
