### ISSUE TITLE
feature request: identical file names with path addition

### ISSUE THREAD

**Issue by dennisosaj** [gejobj/tablist#2]
Hey, I like your extension! And the issue is more like a feature request.

If I open files with a same file name, then it looks like that:
<img width="193" alt="Screenshot 2021-04-30 at 12 41 58" src="https://user-images.githubusercontent.com/48364940/116684625-75777280-a9b1-11eb-818f-b50c699431e6.png">

Nova itself handles it like that in the tabs and add part of the path to the name, like that:
<img width="1291" alt="Screenshot 2021-04-30 at 12 44 17" src="https://user-images.githubusercontent.com/48364940/116684846-c8512a00-a9b1-11eb-986c-6bc4636aabe4.png">

Maybe that would be possible for your extension, too.

Nevertheless... great extension! Missed this feature in Nova, but thanks to you.

**Comment by gejobj** [comment]
Thanks for your comment.
I don't know if nova will let me do that but I will try it.
Best regards and stay tuned ;-)

**Comment by danjguzman** [comment]
I would second this enhancement if possible. It would help determine which files belong to which path, otherwise it's a random game of click-the-file.

**Comment by gejobj** [comment]
Hi.
I try to implement this feature. Now you can see las directory name before file name:
![preview-grouped](https://user-images.githubusercontent.com/9005888/147468475-ae2e8a5a-ed1c-4025-ab4b-b2ef644e52b4.png)
![preview-simple](https://user-images.githubusercontent.com/9005888/147468479-bdd92ae6-0fdb-4fcc-99fc-e521a3e1b45a.png)

You can update it from nova extension panel.

Thanks to all! and Merry Christmas.
