### ISSUE TITLE
bad supported with filename in Chinese

### ISSUE THREAD

**Issue by shidajiangshan** [gejobj/tablist#3]
Chinese filename is unicode...

**Comment by gejobj** [comment]
Sorry, I have no chinese files to see errors :S
I try to fix it. Thanks for reporting the bug.

**Comment by shidajiangshan** [comment]
copy this -&gt; 中文.txt
actually its not a bug, its a encode problem, as UTF-8 and GBK...
u can convert file name from unicode to UTF-8
sorry for my poor English...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gejobj/tablist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gejobj/tablist] bad supported with filename in Chinese (#3)





 
Sorry, I have no chinese files to see errors :S
 I try to fix it. Thanks for reporting the bug.

**Comment by gejobj** [comment]
oh! I see. It seems that Nova applies a utf-8 encoding to the file names to access them. I have added a decode to show the real name int he list.
Thanks for report ^_^
And let me know if you find some issues ;-)
