### ISSUE TITLE
Unaware of tab switching outside of Tab List

### ISSUE THREAD

**Issue by almirramic** [gejobj/tablist#5]
When I switch to a tab using Tab List, it gets highlighted in Tab List. However, if I then switch to another tab using Nova's tab bar, Tab List will be unaware of this and won't highlight it. Then, if I want to switch back to the tab highlighted in Tab List it won't work because it thinks I am still on the previously highlighted tab.

**Comment by gejobj** [comment]
Hi @almirramic

I can't highlight file name when you click on the nova's tab because I 'cant add an event there but I try to solve second tab click.

Best regards.

**Comment by gejobj** [comment]
I see in Nova's API reference:
1.- TreeView has only an [onDidChangeSelection(callback, [thisValue])](https://docs.nova.app/api-reference/tree-view/#ondidchangeselectioncallback-thisvalue)
2.- TreeItem has only an optional [Command](https://docs.nova.app/extensions/commands) to invoke when the item is double-clicked

So... I add a double click to open file if you have file selected and you change it on Nova's tab bar.

This will fix the issue with a double click but I would prefer that TreeView had the onClick option.
If you find another solution, please let me know. 

Best regards.

**Comment by almirramic** [comment]
> Hi @almirramic
> 
> I can't highlight file name when you click on the nova's tab because I 'cant add an event there but I try to solve second tab click.
> 
> Best regards.

Thanks. This fixes it for me. And thanks for developing this.

**Comment by gejobj** [comment]
Thanks to you for using it.
Let me know if you found new issues ;-)
Best regards.
